service: python-api-service
frameworkVersion: '3'
provider:
  name: aws
  runtime: python3.9
functions:
  app:
    handler: app.lambda_handler
    events:
      - httpApi:
          path: /
          method: ANY
      - httpApi:
          path: /{proxy+}
          method: ANY
plugins:
  - serverless-wsgi
  - serverless-python-requirements
custom:
  wsgi:
    app: app.app
